### PR TITLE
Implement PartialEq for Packed*Array and Eq where appropriate

### PR DESCRIPTION
**Pull request by ttencate**
See #33.

### CODE REVIEW

**Comment by Bromeon** [comment]
Thanks, looks nice! 👍 

The named keys for the macro are mostly for expressivity reasons, or is it needed for parsing disambiguation? Arguably some parts are _less_ readable now, because the symbols are no longer aligned.
```diff
-    i64,
-    i64,
-    packed_int64_array_construct_default,
-    packed_int64_array_construct_copy,
-    packed_int64_array_from_array,
-    packed_int64_array_destroy,
-    packed_int64_array_operator_index,
-    packed_int64_array_operator_index_const,
+    type_name: PackedInt64Array,
+    element_type: i64,
+    opaque_type: OpaquePackedInt64Array,
+    inner_type: InnerPackedInt64Array,
+    argument_type: i64,
+    return_type: i64,
+    from_array: packed_int64_array_from_array,
+    operator_index: packed_int64_array_operator_index,
+    operator_index_const: packed_int64_array_operator_index_const,
```

Anyway, that's more bikeshedding 🙂 In general, I wouldn't spend too much time on making this macro look nice, as we're going to rewrite quite a bit once the codegen provides genericity over packed arrays.

**Comment by Bromeon** [comment]
bors try

**Comment by ttencate** [comment]
> The named keys for the macro are mostly for expressivity reasons, or is it needed for parsing disambiguation?

Readability. The argument list got horribly long and it was hard to tell what each argument did. Too bad about the vertical alignment :shrug:

**Comment by Bromeon** [comment]
Fair enough, thanks again! 🙂 

bors r+

**Pull request merged**
